In [1]:
import pandas as pd

Data can be found here: https://covid19.who.int/data

# Daily cases and deaths by date reported to WHO

In [2]:
url = 'https://covid19.who.int/WHO-COVID-19-global-data.csv'
daily_case_deaths = pd.read_csv(url,index_col=0)

In [3]:
daily_case_deaths

,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
Date_reported,,,,,,,
2020-01-03,AF,Afghanistan,EMRO,0,0,0,0
2020-01-04,AF,Afghanistan,EMRO,0,0,0,0
2020-01-05,AF,Afghanistan,EMRO,0,0,0,0
2020-01-06,AF,Afghanistan,EMRO,0,0,0,0
2020-01-07,AF,Afghanistan,EMRO,0,0,0,0
...,...,...,...,...,...,...,...
2022-10-03,ZW,Zimbabwe,AFRO,0,257517,0,5602
2022-10-04,ZW,Zimbabwe,AFRO,0,257517,0,5602
2022-10-05,ZW,Zimbabwe,AFRO,0,257517,0,5602
2022-10-06,ZW,Zimbabwe,AFRO,0,257517,0,5602
2022-10-07,ZW,Zimbabwe,AFRO,0,257517,0,5602

In [4]:
daily_case_deaths.loc[daily_case_deaths['Country'] == 'Saba'] # need to combine  Bonaire, Saint Eustatius and Saba at a later stage

,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
Date_reported,,,,,,,
2020-01-03,XC,Saba,AMRO,0,0,0,0
2020-01-04,XC,Saba,AMRO,0,0,0,0
2020-01-05,XC,Saba,AMRO,0,0,0,0
2020-01-06,XC,Saba,AMRO,0,0,0,0
2020-01-07,XC,Saba,AMRO,0,0,0,0
...,...,...,...,...,...,...,...
2022-10-03,XC,Saba,AMRO,0,730,0,2
2022-10-04,XC,Saba,AMRO,0,730,0,2
2022-10-05,XC,Saba,AMRO,0,730,0,2
2022-10-06,XC,Saba,AMRO,0,730,0,2
2022-10-07,XC,Saba,AMRO,0,730,0,2

In [5]:
'''
display_country = 'Zimbabwe'
daily_case_deaths[daily_case_deaths['Country']== display_country]
'''

"\ndisplay_country = 'Zimbabwe'\ndaily_case_deaths[daily_case_deaths['Country']== display_country]\n"

In [6]:
daily_case_deaths.to_csv(r'./WHO-COVID-19-global-data.csv', encoding='utf-8', header='true')

# Latest reported counts of cases and deaths

In [7]:
url = 'https://covid19.who.int/WHO-COVID-19-global-table-data.csv'
latest_count = pd.read_csv(url,index_col=0)

In [8]:
latest_count

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours
Global,NaN,617597680,7923.465035,2979392,38.224088,469892,6532705,83.811292,8608,0.110436,1492,NaN
United States of America,Americas,95260865,28779.487000,295170,89.175000,61186,1050195,317.277000,2722,0.822000,726,NaN
India,South-East Asia,44606460,3232.342000,19153,1.388000,1997,528754,38.315000,125,0.009000,9,NaN
Brazil,Americas,34699017,16324.385000,44827,21.089000,7121,686573,323.003000,646,0.304000,109,NaN
France,Europe,34665044,53298.563000,360445,554.195000,65122,151793,233.386000,288,0.443000,49,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Tuvalu,Western Pacific,20,169.607000,0,0.000000,0,0,0.000000,0,0.000000,0,NaN
Pitcairn Islands,Western Pacific,4,8000.000000,0,0.000000,0,0,0.000000,0,0.000000,0,NaN
Democratic People's Republic of Korea,South-East Asia,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,NaN
Tokelau,Western Pacific,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,NaN
Turkmenistan,Europe,0,0.000000,0,0.000000,0,0,0.000000,0,0.000000,0,NaN

In [9]:
latest_count.to_csv(r'./WHO-COVID-19-global-table-data.csv', encoding='utf-8', header='true')

# Vaccination Data

In [10]:
url = 'https://covid19.who.int/who-data/vaccination-data.csv'
vac_data = pd.read_csv(url,index_col=0)

In [11]:
vac_data

,ISO3,WHO_REGION,DATA_SOURCE,DATE_UPDATED,TOTAL_VACCINATIONS,PERSONS_VACCINATED_1PLUS_DOSE,TOTAL_VACCINATIONS_PER100,PERSONS_VACCINATED_1PLUS_DOSE_PER100,PERSONS_FULLY_VACCINATED,PERSONS_FULLY_VACCINATED_PER100,VACCINES_USED,FIRST_VACCINE_DATE,NUMBER_VACCINES_TYPES_USED,PERSONS_BOOSTER_ADD_DOSE,PERSONS_BOOSTER_ADD_DOSE_PER100
COUNTRY,,,,,,,,,,,,,,,
Afghanistan,AFG,EMRO,REPORTING,2022-10-04,11923733.0,10961643.0,30.630,28.159,10278516.0,26.404,"AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-C...",2021-02-22,11.0,NaN,NaN
Albania,ALB,EURO,REPORTING,2022-09-18,2974247.0,1336938.0,103.400,46.977,1262982.0,44.378,"AstraZeneca - Vaxzevria,Gamaleya - Gam-Covid-V...",2021-01-13,5.0,356077.0,12.512
Algeria,DZA,AFRO,REPORTING,2022-09-04,15267442.0,7840131.0,34.817,17.879,6481186.0,14.780,"Beijing CNBG - BBIBP-CorV,Gamaleya - Gam-Covid...",2021-01-30,4.0,575651.0,1.313
American Samoa,ASM,WPRO,REPORTING,2022-08-23,111316.0,44885.0,201.670,81.318,41423.0,75.046,"Janssen - Ad26.COV 2-S,Moderna - Spikevax,Pfiz...",2020-12-21,3.0,24160.0,43.770
Andorra,AND,EURO,REPORTING,2022-09-11,154235.0,57894.0,199.600,75.999,53480.0,70.205,"AstraZeneca - Vaxzevria,Moderna - Spikevax,Pfi...",2021-01-20,3.0,42861.0,56.265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Viet Nam,VNM,WPRO,REPORTING,2022-09-22,259794452.0,89975153.0,266.898,92.435,84234230.0,86.537,"AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-C...",2021-03-08,6.0,55718009.0,57.241
Wallis and Futuna,WLF,WPRO,REPORTING,2022-07-26,16782.0,6592.0,149.226,58.616,6989.0,62.147,Moderna - Spikevax,2021-03-19,1.0,3201.0,28.463
Yemen,YEM,EMRO,REPORTING,2022-09-28,1065395.0,861625.0,3.572,2.889,604202.0,2.026,"AstraZeneca - Vaxzevria,Beijing CNBG - BBIBP-C...",2021-04-20,11.0,33507.0,0.112
Zambia,ZMB,AFRO,REPORTING,2022-09-25,9315275.0,8233510.0,50.671,44.786,6043203.0,32.872,"Beijing CNBG - BBIBP-CorV,Janssen - Ad26.COV 2...",2021-04-14,3.0,668550.0,3.637
Zimbabwe,ZWE,AFRO,REPORTING,2022-10-02,12573027.0,6530782.0,84.593,43.940,4883871.0,32.859,"Beijing CNBG - BBIBP-CorV,Bharat - Covaxin,Gam...",2021-02-18,4.0,1158374.0,7.794

In [12]:
vac_data.to_csv(r'./vaccination-data.csv', encoding='utf-8', header='true')

# Vaccination metadata

In [13]:
url = 'https://covid19.who.int/who-data/vaccination-metadata.csv'
vac_metadata= pd.read_csv(url,index_col=0)

In [14]:
vac_metadata

,VACCINE_NAME,PRODUCT_NAME,COMPANY_NAME,AUTHORIZATION_DATE,START_DATE,END_DATE,COMMENT,DATA_SOURCE
ISO3,,,,,,,,
SHN,AstraZeneca - AZD1222,AZD1222,AstraZeneca,NaN,NaN,NaN,NaN,OWID
GRL,Moderna - mRNA-1273,mRNA-1273,Moderna,NaN,NaN,NaN,NaN,OWID
FRO,Moderna - mRNA-1273,mRNA-1273,Moderna,NaN,NaN,NaN,NaN,OWID
FRO,Pfizer BioNTech - Comirnaty,Comirnaty,Pfizer BioNTech,NaN,NaN,NaN,NaN,OWID
BIH,AstraZeneca - AZD1222,AZD1222,AstraZeneca,NaN,NaN,NaN,NaN,OWID
...,...,...,...,...,...,...,...,...
TKM,Unknown Vaccine,Unknown Vaccine,NaN,NaN,2022-03-02,NaN,NaN,REPORTING
UZB,Unknown Vaccine,Unknown Vaccine,NaN,NaN,2021-05-12,NaN,NaN,REPORTING
MCO,Novavax - Covavax,Covavax,NaN,NaN,2022-03-30,NaN,NaN,REPORTING
THA,SII - Covovax,Covovax,NaN,2022-04-27,NaN,NaN,NaN,REPORTING
IND,SII - Covovax,Covovax,NaN,NaN,NaN,NaN,NaN,REPORTING

In [15]:
vac_metadata.to_csv(r'./vaccination-metadata.csv', encoding='utf-8', header='true')